### ISSUE TITLE
BUG: Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: calculated final stake for delegator 

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#1107]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Looks like withdraw rewards command isnt working. 

```
palomad tx distribution withdraw-rewards ${VALIDATOR} --commission --yes --from ${KEY} --chain-id messenger --gas=auto --gas-prices=0.04ugrain --gas-adjustment 1.8
```
Returns the error: 

Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: calculated final stake for delegator paloma1s0lankh33kprer2l22nank5rvsuh9ksaxkx852 greater than current stake
        final stake:    170445700572.000000000000000000
        current stake:  167053831146.243955883630225116

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

palomad version: 1.13.0
pigeon version:  v1.11.0

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

May only impact validator commands? We will check.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

no rpc errors on withdraw.

**Comment by aditya-manit** [comment]
```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: calculated final stake for delegator paloma1s0lankh33kprer2l22nank5rvsuh9ksaxkx852 greater than current stake
        final stake:    170445700572.000000000000000000
        current stake:  167053831146.243955883630225116
stack:
goroutine 372364 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func5({0x2d03080?, 0xc0d726c4d0})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/recovery.go:74 +0x26
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func7({0x2d03080?, 0xc0d726c4d0?})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/recovery.go:42 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2d03080, 0xc0d726c4d0}, 0x0?)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/recovery.go:31 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2d03080, 0xc0d726c4d0}, 0x0?)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/recovery.go:36 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/baseapp.go:836 +0x136
panic({0x2d03080?, 0xc0d726c4d0?})
        /opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:920 +0x270
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.CalculateDelegationRewards({{0x3c04ea0, 0xc000137570}, {0x3c5a840, 0xc0018ba590}, {0x3c42be0, 0xc00126cdc0}, {0x7f9c4437e748, 0xc0005ca500}, {0x3c57e00, 0xc000ba0280}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/distribution/keeper/delegation.go:177 +0x8bb
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.withdrawDelegationRewards({{0x3c04ea0, 0xc000137570}, {0x3c5a840, 0xc0018ba590}, {0x3c42be0, 0xc00126cdc0}, {0x7f9c4437e748, 0xc0005ca500}, {0x3c57e00, 0xc000ba0280}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/distribution/keeper/delegation.go:222 +0x26b
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.WithdrawDelegationRewards({{0x3c04ea0, 0xc000137570}, {0x3c5a840, 0xc0018ba590}, {0x3c42be0, 0xc00126cdc0}, {0x7f9c4437e748, 0xc0005ca500}, {0x3c57e00, 0xc000ba0280}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/distribution/keeper/keeper.go:127 +0x15e
github.com/cosmos/cosmos-sdk/x/distribution/keeper.msgServer.WithdrawDelegatorReward({{{0x3c04ea0, 0xc000137570}, {0x3c5a840, 0xc0018ba590}, {0x3c42be0, 0xc00126cdc0}, {0x7f9c4437e748, 0xc0005ca500}, {0x3c57e00, 0xc000ba0280}, ...}}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/distribution/keeper/msg_server.go:59 +0x269
github.com/cosmos/cosmos-sdk/x/distribution/types._Msg_WithdrawDelegatorReward_Handler.func1({0x3c40058, 0xc00d42e0c0}, {0x31998c0?, 0xc0018a92a0})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/distribution/types/tx.pb.go:1173 +0x72
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2.1({0x3c3f198, 0xc003f26e00}, {0xc0e19d8d78?, 0x411da5?}, 0x358?, 0xc00e35bb18)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/msg_service_router.go:175 +0x93
github.com/cosmos/cosmos-sdk/x/distribution/types._Msg_WithdrawDelegatorReward_Handler({0x33203e0?, 0xc000fe0a00}, {0x3c3f198, 0xc003f26e00}, 0x361beb0, 0xc0018a9a60)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/distribution/types/tx.pb.go:1175 +0x135
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2({{0x3c3f5f8, 0x5aefe00}, {0x3c5b680, 0xc00e986d40}, {{0x0, 0x0}, {0xc0018b94a3, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/msg_service_router.go:198 +0x363
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x3c3f5f8, 0x5aefe00}, {0x3c5b680, 0xc00e986d40}, {{0x0, 0x0}, {0xc0018b94a3, 0x9}, 0x0, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/baseapp.go:1009 +0x1e6
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000f72480, 0x2, {0xc0e03731e0, 0x182, 0x1a0})
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/baseapp.go:947 +0x116c
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/test_helpers.go:28
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x3c637a0, 0xc000fe2960}, 0x0, {0x0, 0x0}, {0x3c7d068, 0xc000efedc0}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/x/auth/tx/service.go:98 +0x129
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x31b7ac0?, 0xc000275c20}, {0x3c3f198, 0xc00171d880}, 0xc00e35ac00, 0x0)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/types/tx/service.pb.go:1436 +0x169
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).registerABCIQueryHandler.func1({{0x3c3f5f8, 0x5aefe00}, {0x3c5b680, 0xc00e986a80}, {{0x0, 0x0}, {0xc0018b94a3, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/grpcrouter.go:109 +0xcf
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc000f72480, 0xc000fe2990, 0xc018f6f680)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/abci.go:1139 +0x1bd
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc000f72480, {0x0?, 0xc0e1906b90?}, 0xc018f6f680)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/abci.go:177 +0x631
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Query(...)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/cmt_abci.go:24
github.com/cometbft/cometbft/abci/client.(*localClient).Query(0xc001781260?, {0x3c40138?, 0x5aefe00?}, 0x40?)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:106 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnQuery).Query(0xc0015dd458, {0x3c40138, 0x5aefe00}, 0x3?)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:181 +0x170
github.com/cometbft/cometbft/rpc/core.(*Environment).ABCIQuery(0xc000f72000, 0x5000b?, {0xc097a645d0, 0x23}, {0xc0a9089880, 0x185, 0x380}, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/rpc/core/abci.go:22 +0xdf
reflect.Value.call({0x2eb34c0?, 0xc0012996f0?, 0x3330620?}, {0x334ad6c, 0x4}, {0xc0e0f7dd00, 0x5, 0x41ac32?})
        /opt/hostedtoolcache/go/1.21.8/x64/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0x2eb34c0?, 0xc0012996f0?, 0x35d?}, {0xc0e0f7dd00?, 0x3330620?, 0xc0e0cb0100?})
        /opt/hostedtoolcache/go/1.21.8/x64/src/reflect/value.go:380 +0xb9
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3({0x3c34390, 0xc0265d1200}, 0xc000b5e900)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/rpc/jsonrpc/server/http_json_handler.go:108 +0xcf0
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4({0x3c34390?, 0xc0265d1200?}, 0x7f9c0fbb9818?)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/rpc/jsonrpc/server/http_json_handler.go:140 +0x42
net/http.HandlerFunc.ServeHTTP(0xc0010b6c00?, {0x3c34390?, 0xc0265d1200?}, 0xc0e1907968?)
        /opt/hostedtoolcache/go/1.21.8/x64/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0xc0010b6c00?, {0x3c34390, 0xc0265d1200}, 0xc000b5e900)
        /opt/hostedtoolcache/go/1.21.8/x64/src/net/http/server.go:2514 +0x142
github.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x3c045e0?, 0xc001ae8540?}, 0xd?}, {0x3c34390?, 0xc0265d1200}, 0xc000b5e900)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/rpc/jsonrpc/server/http_server.go:256 +0x11c
github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x3c1f570?, 0xc001019b20}, 0xc000b5e900)
        /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/rpc/jsonrpc/server/http_server.go:229 +0x26f
net/http.HandlerFunc.ServeHTTP(0x414645?, {0x3c1f570?, 0xc001019b20?}, 0xc001019b01?)
        /opt/hostedtoolcache/go/1.21.8/x64/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0x3c165f8?}, {0x3c1f570?, 0xc001019b20?}, 0x6?)
        /opt/hostedtoolcache/go/1.21.8/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc005d2d320, {0x3c40058, 0xc001a39260})
        /opt/hostedtoolcache/go/1.21.8/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 33
        /opt/hostedtoolcache/go/1.21.8/x64/src/net/http/server.go:3086 +0x5cb
: panic [cosmos/cosmos-sdk@v0.50.5/baseapp/recovery.go:72] with gas used: '64344': unknown request
Usage:
  palomad tx distribution withdraw-rewards [validator-addr] [flags]
```

**Comment by aditya-manit** [comment]
Does the withdraw amount in your case was greater than the current delegated amount ? I think that when it gives the above message !

**Comment by taariq** [comment]
Fixed with upgrade of Paloma and iavl.
