### ISSUE TITLE
BUG: Pigeon crash `Valset ID mismatch`

### ISSUE THREAD

**Issue by kinrokinro** [palomachain/paloma#1314]
# What is happening?
Pigeon always crashes when validator is in active validator set

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

```
$ /usr/local/bin/pigeon version
App version: v2.3.1
Build commit hash: 5f6f4bcaa645e0f9d8530b24cd1a4cd74b79e857
$ ~/.paloma/cosmovisor/current/bin/palomad version
v2.3.2
```

```
time="2024-10-25T17:15:47Z" level=info msg="estimator loop"
time="2024-10-25T17:15:47Z" level=warning msg="Valset ID mismatch. Swallowing error to retry message..." chain-reference-id=base-main component=skyway-relay-batch skyway-batch-nonce=13 x-correlation-id=csdt4g3ajpmei9voeirg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2545823]
goroutine 74 [running]:
github.com/ethereum/go-ethereum/core/types.(*Transaction).Gas(...)
        /home/ubuntu/go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101311.0/core/types/transaction.go:296
github.com/palomachain/pigeon/chain/evm.compass.skywayEstimateBatches({{0x357fea0, 0xc0013aa2c0}, {0x357e3f8, 0xc0015aa300}, 0xc000c78908, 0xc0016431a0, {0xc001645e40, 0x20}, {0xc001034264, 0x9}, ...}, ...)
        /home/ubuntu/pigeon/chain/evm/compass.go:1520 +0x4e3
github.com/palomachain/pigeon/chain/evm.Processor.SkywayEstimateBatches({0xc000fd5950, 0xc0015aa300, {0x2c3f8b0, 0x3}, {0xc001034264, 0x9}, {0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
        /home/ubuntu/pigeon/chain/evm/processor.go:173 +0xec
github.com/palomachain/pigeon/relayer.(*Relayer).skywayEstimateBatchGas(0xc00134aa80, {0x3566b78, 0xc000f8fe60}, {0xc001380b00?, 0x1?, 0x27d1e40?})
        /home/ubuntu/pigeon/relayer/skyway_batch_estimator.go:60 +0x47a
github.com/palomachain/pigeon/relayer.(*Relayer).SkywayEstimateBatchGas(0xc00134aa80, {0x3566b78, 0xc000f8fe60}, {0x3542ec0, 0xc000be7310})
        /home/ubuntu/pigeon/relayer/skyway_batch_estimator.go:26 +0x166
github.com/palomachain/pigeon/relayer.(*Relayer).startProcess(0xc00134aa80, {0x3566bb0, 0xc00136b9f0}, {0x2c6c888, 0x19}, {0x3542ec0, 0xc000be7310}, 0x12a05f200?, 0x1, 0xc00106a960)
        /home/ubuntu/pigeon/relayer/start.go:58 +0x39c
created by github.com/palomachain/pigeon/relayer.(*Relayer).Start in goroutine 1
        /home/ubuntu/pigeon/relayer/start.go:93 +0x971
pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by taariq** [comment]
Fixed https://github.com/palomachain/pigeon/pull/451
