### ISSUE TITLE
bug: unable to locate keyring ENV variable

### ISSUE THREAD

**Issue by CoreDov** [palomachain/paloma#309]
```shell
root@CoreDov-VM:~$ pigeon start
*chirp chirp*
panic: unable to locate keyring ENV variable

goroutine 1 [running]:
github.com/palomachain/pigeon/config.KeyringPassword(...)
        /app/config/config.go:88
github.com/palomachain/pigeon/app.PalomaClient()
        /app/app/app.go:129 +0x2fb
github.com/palomachain/pigeon/app.Relayer()
        /app/app/app.go:42 +0x45
main.glob..func11(0x23322e0, {0x14755de?, 0x0?, 0x0?})
        /app/cmd/pigeon/cmd_start.go:16 +0x5c
github.com/spf13/cobra.(*Command).execute(0x23322e0, {0x23f4c10, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2332060)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /app/cmd/pigeon/main.go:4 +0x25
```

**Comment by taariq** [comment]
Fixed with latest release.

**Comment by MattiaFailla** [comment]
Unfortunately the bug is still present in v0.11.0

```
jelly@paloma:~$ pigeon start
*chirp chirp*
INFO[0000] app info                                      PID=3781 commit=a84b3dc384fd26136fd4f1abb24468d7a27f653d version=v0.11.0
INFO[0000] Starting healthcheck server                  
panic: unable to locate keyring ENV variable

goroutine 1 [running]:
github.com/palomachain/pigeon/config.KeyringPassword(...)
        /app/config/config.go:84
github.com/palomachain/pigeon/app.PalomaClient()
        /app/app/app.go:127 +0x37a
main.glob..func15(0x2400ea0, {0x14f0610?, 0x0?, 0x0?})
        /app/cmd/pigeon/cmd_start.go:47 +0x35a
github.com/spf13/cobra.(*Command).execute(0x2400ea0, {0x24c5090, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2400c20)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /app/cmd/pigeon/main.go:32 +0xbb
```
