### ISSUE TITLE
bug: there is a problem after upgrading version

### ISSUE THREAD

**Issue by sanXsan** [palomachain/paloma#331]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Provide relevant software versions, screenshots, copy & paste error messages and so on.
Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

previously i was running version v0.2.5-prealpha everything was fine no problem in my machine, then i got error message palomad upgrade needed, then i upgraded to v0.3.0-alpha, and started running , error like this

```
6:19PM INF starting node with ABCI Tendermint in-process
6:19PM INF Starting multiAppConn service impl=multiAppConn module=proxy
6:19PM INF Starting localClient service connection=query impl=localClient module=abci-client
6:19PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
6:19PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
6:19PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
6:19PM INF Starting EventBus service impl=EventBus module=events
6:19PM INF Starting PubSub service impl=PubSub module=pubsub
6:19PM INF Starting IndexerService service impl=IndexerService module=txindex
6:19PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.3.0-alpha
6:19PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
6:19PM INF asserting crisis invariants inv=0/11 module=x/crisis name=gov/module-account
6:19PM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/nonnegative-outstanding
6:19PM INF asserting crisis invariants inv=2/11 module=x/crisis name=bank/total-supply
6:19PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/nonnegative-outstanding
6:19PM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/can-withdraw
6:19PM INF asserting crisis invariants inv=5/11 module=x/crisis name=distribution/reference-count
6:19PM INF asserting crisis invariants inv=6/11 module=x/crisis name=distribution/module-account
6:19PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
6:19PM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
6:19PM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
6:19PM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
6:19PM INF asserted all invariants duration=2.671418 height=0 module=x/crisis
6:19PM INF created new capability module=ibc name=ports/transfer
6:19PM INF port binded module=x/ibc/port port=transfer
6:19PM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: unknown field "chains" in types.Params

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0002700f0?, {0xc000f9c420?, 0xc0001da570?, 0x25b77e0?}, {0x25c94d0?, 0x3637af0?})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45
github.com/palomachain/paloma/x/evm.AppModule.InitGenesis({{{0x25d9be0, 0xc00111d5c0}}, {{0x25d9be0, 0xc00111d5c0}, {0x25ba7a0, 0xc000ef9120}, {0x25ba7a0, 0x0}, {{0x25d9be0, 0xc00111d5c0}, ...}, ...}, ...}, ...)
        /app/x/evm/module.go:153 +0x62
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x25ce768, 0xc0000520f0}, {0x25db300, 0xc000062bc0}, {{0x0, 0x0}, {0xc000de2600, 0x10}, 0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d
github.com/palomachain/paloma/app.(*App).InitChainer(_, {{0x25ce768, 0xc0000520f0}, {0x25db300, 0xc000062bc0}, {{0x0, 0x0}, {0xc000de2600, 0x10}, 0x0, ...}, ...}, ...)
        /app/app/app.go:684 +0x20e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000f53380, {{0xab046b1, 0xeda4fb12c, 0x0}, {0xc000de2600, 0x10}, 0xc000285a40, {0x3637af0, 0x0, 0x0}, ...})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001102240, {{0xab046b1, 0xeda4fb12c, 0x0}, {0xc000de2600, 0x10}, 0xc000285a40, {0x3637af0, 0x0, 0x0}, ...})
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0xab046b1, 0xeda4fb12c, 0x0}, {0xc000de2600, 0x10}, 0xc000285a40, {0x3637af0, 0x0, 0x0}, ...})
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1c9bf05, 0x7}}, {0xc000de2600, 0x10}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0029ddf68, {0x25dbcf8, 0xc000e6ed00})
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1c9bf05, 0x7}}, {0xc000de2600, 0x10}, 0x1, 0x0, ...}, ...)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0001f0dc0, {0x25cb630, 0xc0003a9720}, 0xc000d0ebf0, {0x25b5880, 0xc000263ea8}, 0x0?, 0x0?, 0xc000d0ee00, {0x25cf610, ...}, ...)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x25e2460, 0xc0001dffb0}, {0xc000e251c0, 0x10}, {0x25d2980, 0xc00111d5c0}, ...}, ...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0001fb680?, {0x3637af0?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0001fb680, {0x3637af0, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000155900)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com//spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x237cb98?, {0xc00111ebb0, 0xd})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        /app/cmd/palomad/main.go:52 +0xc5
palomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
palomad.service: Failed with result 'exit-code'.spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x237cb98?, {0xc00111ebb0, 0xd})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        /app/cmd/palomad/main.go:52 +0xc5
palomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
palomad.service: Failed with result 'exit-code'.
```

I tried to re-install the latest binary but it didn't work and finally I reinstalled the server and started everything from scratch with the new version of the binary still error

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

{WRITE YOUR ANSWER HERE}

**Comment by taariq** [comment]
Closing so user can re-open with new data

**Comment by measure-fi** [comment]
Seems to affect other fresh installs, but probably requires a fix in the go code.

**Comment by rootedbox** [comment]
using a snapshot fixes the issue https://nodejumper.io/paloma-testnet/sync so this should only effect new users.

**Comment by Vizualni** [comment]
Given that @rootedbox 's comment fixes the issue, I am closing this bug ticket. Thanks!
