### ISSUE TITLE
Bug: paloma.py query block height runs into 404 errors

### ISSUE THREAD

**Issue by fieldtheory123** [palomachain/paloma#533]
# What is happening?
When using paloma.py to query block height, I run into 404 errors.  
  <summary>Section description</summary>
<i>chain: testnet

paloma_sdk version: 3.0.2
</i>
Logs:

$ python -i
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> from paloma_sdk.client.lcd import LCDClient
>>> url_="http://testnet.palomaswap.com:26656/"
>>> url_
'http://testnet.palomaswap.com:26656/'
>>> chain_id_="paloma-testnet-10"
>>> paloma=LCDClient(chain_id=chain_id_,url=url_)
>>> paloma.tendermint.block_info()['block']['header']['height']
Traceback (most recent call last):
  File "C:\Users\zz\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py", line 114, in _get
    result = await response.json(content_type=None)
  File "C:\Users\zz\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
  File "C:\Users\zz\Anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\zz\Anaconda3\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zz\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "C:\Users\zz\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "C:\Users\zz\Anaconda3\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\Users\zz\Anaconda3\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\zz\Anaconda3\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\Users\zz\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\api\tendermint.py", line 62, in block_info
    return await self._c._get(f"/cosmos/base/tendermint/v1beta1/blocks/{x}", params)
  File "C:\Users\zz\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py", line 298, in _get
    result = await super()._get(*args, **kwargs)
  File "C:\Users\zz\Anaconda3\lib\site-packages\paloma_sdk\client\lcd\lcdclient.py", line 116, in _get
    raise LCDResponseError(message=str(response.reason), response=response)
paloma_sdk.exceptions.LCDResponseError: Status 404 - Not Found

{WRITE YOUR ANSWER HERE}

**Comment by verabehr** [comment]
there is an issue with the port that ngnix is pointed to. @rootedbox will fix, so port changes won't affect this SDK in the future. 

@fieldtheory123 also noticed that you're still pointing to testnet 10. Please swap to ```chain_id_="paloma-testnet-12"```

@rootedbox Please close this issue when your change was made and the readme was updated to avoid these mixups in the future.

**Comment by fieldtheory123** [comment]
@verabehr @rootedbox The issue has been fixed. The following code works. Closing this ticket. thx

from paloma_sdk.client.lcd import LCDClient
paloma = LCDClient(chain_id="paloma-testnet-12", url="https://testnet.palomaswap.com")
block_info['result']['block']['header']['height']

**Comment by taariq** [comment]
Very nice!
