### ISSUE TITLE
bug: Non-funded transactions are failing.

### ISSUE THREAD

**Issue by wc117** [palomachain/paloma#636]
# What is happening?
<details>
  <summary>Non-funded transactions are failing. This doesn't mean non-gas-fee transactions. Except for storing code transactions, the transaction sender should send at least `1ugrain`. Otherwise, the gas estimation and the transaction fail.</summary>
</details>

# Paloma and pigeon versions and logs
<details>
  <summary>Paloma 0.11.4</summary>
</details>

# How to reproduce?
<details>
  <summary>Any wasm transaction except storing code transaction on Paloma.</summary>
</details>

# What is the expected behavior?
<details>
  <summary>In my opinion, all the transactions don't need to contain funds. Of course, in some cases, we need funded transactions.</summary>
</details>

**Comment by taariq** [comment]
@wc117 do you have an error you are able to post to this ticket please? We need the error logs.

**Comment by wc117** [comment]
I was going to instantiate CW20 code.
https://github.com/palomachain/paloma.py/blob/features/detect-lcd-errors/integration_tests/tx_gas_estimate.py
This fails with following errors.
```
https://lcd.testnet.palomaswap.com/cosmos/auth/v1beta1/accounts/paloma1x46rqay4d3cssq8gxxvqz8xt6nwlz4td5wpjhf
Tx(body=TxBody(messages=[MsgInstantiateContract(sender='paloma1x46rqay4d3cssq8gxxvqz8xt6nwlz4td5wpjhf', admin=None, code_id=49, label='CW20', msg={'name': 'CW20 Token', 'symbol': 'CWFT', 'decimals': 9, 'initial_balances': [{'address': 'paloma1x46rqay4d3cssq8gxxvqz8xt6nwlz4td5wpjhf', 'amount': '1000000000000000'}]}, funds=Coins('0ugrain'))], memo='', timeout_height=0), auth_info=AuthInfo(signer_infos=[SignerInfo(public_key=SimplePublicKey(key=b'\x02;3\xa8RCD\x06\x1b\x126L\xba \xfe\n\x1a\xb3mD\x86\xab\xf4Q\xbb|\xeb\xd1\x1e\xa2$\x1e['), mode_info=ModeInfo(single=ModeInfoSingle(mode=<SignMode.SIGN_MODE_DIRECT: 1>), multi=None), sequence=0)], fee=Fee(gas_limit=0, amount=Coins(), payer=None, granter=None)), signatures=[b' '])
CqACCp0CCigvY29zbXdhc20ud2FzbS52MS5Nc2dJbnN0YW50aWF0ZUNvbnRyYWN0EvABCi1wYWxvbWExeDQ2cnFheTRkM2Nzc3E4Z3h4dnF6OHh0Nm53bHo0dGQ1d3BqaGYYMSIEQ1cyMCqpAXsibmFtZSI6ICJDVzIwIFRva2VuIiwgInN5bWJvbCI6ICJDV0ZUIiwgImRlY2ltYWxzIjogOSwgImluaXRpYWxfYmFsYW5jZXMiOiBbeyJhZGRyZXNzIjogInBhbG9tYTF4NDZycWF5NGQzY3NzcThneHh2cXo4eHQ2bndsejR0ZDV3cGpoZiIsICJhbW91bnQiOiAiMTAwMDAwMDAwMDAwMDAwMCJ9XX0yCwoGdWdyYWluEgEwElIKTgpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQI7M6hSQ0QGGxI2TLog/goas21Ehqv0Ubt869EeoiQeWxIECgIIARIAGgEg
Traceback (most recent call last):
  File "tx_gas_estimate.py", line 56, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "tx_gas_estimate.py", line 39, in main
    tx = await test.create_and_sign_tx(CreateTxOptions(
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/wallet.py", line 52, in create_and_sign_tx
    tx=(await self.create_tx(options)),
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/wallet.py", line 37, in create_tx
    return await self.lcd.tx.create(sigOpt, options)
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/api/tx.py", line 176, in create
    opt.fee = await BaseAsyncAPI._try_await(self.estimate_fee(signer_data, opt))
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/api/_base.py", line 19, in _try_await
    return await aw
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/api/tx.py", line 219, in estimate_fee
    gas = str(await super()._try_await(self.estimate_gas(tx, opt)))
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/api/_base.py", line 19, in _try_await
    return await aw
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/api/tx.py", line 232, in estimate_gas
    res = await self._c._post(
  File "/home/wc117/my_env/lib/python3.8/site-packages/paloma_sdk/client/lcd/lcdclient.py", line 131, in _post
    raise LCDResponseError(message=result.get("message"), response=response)
paloma_sdk.exceptions.LCDResponseError: Status 500 - rpc error: code = Unknown desc = invalid coins With gas wanted: '0' and gas used: '19998' : unknown request
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f939bbd75b0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f939bbda6a0>, 603927.538)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f939bbd7610>
```
This is an error from gas estimation.
If I uncomment the Line 48 code, it fails with the following errors.
```
https://lcd.testnet.palomaswap.com/cosmos/auth/v1beta1/accounts/paloma1x46rqay4d3cssq8gxxvqz8xt6nwlz4td5wpjhf
BlockTxBroadcastResult(height=0, txhash='E506C67F6A5F91DCEBE8DFE64B436714988AD01CF5A14AC10E5D45CE721AF907', raw_log='invalid coins', gas_wanted=0, gas_used=6666, logs=None, code=10, codespace='sdk', info=None, data=None, timestamp=None)
```
When I change Line 38 from "0ugrain" to "1ugrain", it works fine.

**Comment by alexanderbez** [comment]
So `0ugrain` is not a valid token, specifically the 0 part. You need to either submit positive amount or `nil`. I don't know the Python tools you're using, so I'm not sure how it's being broadcasted.

Based on the error log, it looks like it failed the AnteHandler, thus you're submitting it with `0ugrain` is going to work. If you want to pay no fees, then you must submit a `nil` value.

**Comment by taariq** [comment]
Closing with submit nil value.
