### ISSUE TITLE
Metamask and Nest Wallet disconnect error

### ISSUE THREAD

**Issue by KyErgus** [palomachain/paloma#737]
# Metamask and Nest Wallet disconnect error

There is no problem connecting Metamask wallet and Nest wallet on [palomaswap.com](https://www.palomaswap.com/uniswap-v2/)  But when you try to disconnect the wallets, if you go out of a certain order, an error occurs in the application and it does not get fixed. For example, we connect Metamask first and then Nest wallet. But when Metamask starts disconnecting wallets from wallet, the following error occurs. so if the user doesn't want to get an error, when disconnecting the wallets, they should start with the Nest wallet first.

`framework-bb5c596eafb42b22.js:1 TypeError: Cannot read properties of null (reading 'substr')
       at Object.shorten (866-2a15bc06ab551c6c.js:1:11755)
       at F (866-2a15bc06ab551c6c.js:1:6247)
       at oo (framework-bb5c596eafb42b22.js:1:59416)
       at Ku (framework-bb5c596eafb42b22.js:1:111716)
       at Li (framework-bb5c596eafb42b22.js:1:98957)
       at Ni (framework-bb5c596eafb42b22.js:1:98885)
       at Pi (framework-bb5c596eafb42b22.js:1:98748)
       at bi (framework-bb5c596eafb42b22.js:1:95714)
       at framework-bb5c596eafb42b22.js:1:45208
       at t.unstable_runWithPriority (framework-bb5c596eafb42b22.js:1:129354) `

The picture of the error is in the link: 
https://www.dropbox.com/s/j15vvtm3c6m0d6c/IMG-20230227-WA0011.jpg?dl=0

- Operating system: MacOs Monterey 12.6
- Internet browser used: Google Chrome is up to date
Version 110.0.5481.77 (Official Build) (x86_64)
- Wallet Version: Paloma Nest(Beta) 1.3.4 Beta

**Comment by verabehr** [comment]
@wdev733 I can reliably reproduce. Loom is attached: https://www.loom.com/share/709a588b8e84413f9305dcb70561e799
