### ISSUE TITLE
Error with pigeon and can't unjail. This error too

### ISSUE THREAD

**Issue by Dimarchik** [palomachain/paloma#837]
Started Pigeon Service.
*coo! coo!*
time="2023-05-15T20:58:02+02:00" level=info msg="app info" PID=1080159 commit=cd14972b74003d3613963f552752e6bcde826fe4 version=v0.11.5
time="2023-05-15T20:58:02+02:00" level=info msg="Starting healthcheck server"
panic: Bytes left over in UnmarshalBinaryLengthPrefixed, should read 10 more bytes but have 153
goroutine 1 [running]:
github.com/palomachain/pigeon/chain/paloma.getMainAddress({0xc000d3d970, {{{0xc000da4b70, 0x4}, {0xc000da4c20, 0x6}, {0xc000da4bf0, 0xb}}, {{0xc000b23320, 0x16}, {0xc000da4b80, ...}, ...}, ...}, ...})
        /app/chain/paloma/client.go:420 +0xbe
github.com/palomachain/pigeon/chain/paloma.getCreator({0xc000d3d970, {{{0xc000da4b70, 0x4}, {0xc000da4c20, 0x6}, {0xc000da4bf0, 0xb}}, {{0xc000b23320, 0x16}, {0xc000da4b80, ...}, ...}, ...}, ...})
        /app/chain/paloma/client.go:426 +0x5a
github.com/palomachain/pigeon/chain/paloma.(*Client).Init(0xc000b33600)
        /app/chain/paloma/client.go:49 +0xa5
github.com/palomachain/pigeon/app.PalomaClient()
        /app/app/app.go:141 +0x314
main.glob..func15(0x2404ea0, {0x14f2670?, 0x0?, 0x0?})
        /app/cmd/pigeon/cmd_start.go:47 +0x35a
github.com/spf13/cobra.(*Command).execute(0x2404ea0, {0x24c90b0, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2404c20)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /app/cmd/pigeon/main.go:32 +0xbb
pigeond.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
pigeond.service: Failed with result 'exit-code'.
pigeond.service: Scheduled restart job, restart counter is at 2.
Stopped Pigeon Service.

**Comment by Dimarchik** [comment]
ok. thak's
